kind: pipeline
name: "Supabase task CI/CD part"

steps:
- name: "Verify & build"
  image: node:alpine
  environment:
    NEXT_PUBLIC_SUPABASE_URL:
      from_secret: base_url
    NEXT_PUBLIC_SUPABASE_ANON_KEY:
      from_secret: anon_key
  commands:
    - cd supabase_task
    - npm install
    - npm run build

- name: "Build docker image"
  image: plugins/docker
  environment:
    TOKEN:
      from_secret: docker_token
  settings:
    repo: docker.io/maxmoskalenko/supabase_app
    tags: [ "${DRONE_COMMIT_SHA:0:7}","latest" ]
    username:
      from_secret: docker_user
    password:
      from_secret: docker_pass
    build_args_from_env:
      - TOKEN
  commands:
    - cd supabase_task
    - docker build . -t supabase-app
    - image_line=$(docker image ls | grep "supabase-app")
    - image_id=$(echo $image | cut -d' ' -f 3)
    - image_tag=$(echo maxmoskalenko/supabase_app:${image_id:0:7})
    - docker tag $image_id $image_tag
    - docker push $image_tag

trigger:
  branch:
    - dev
  event:
    - push