kind: pipeline
type: docker
name: default

steps:
- name: "Verify & build"
  image: next:alpine
  commands:
    - cd supabase_task
    - npm install
    - npm run build
    - npm run start
     
trigger:
  branch:
    - dev
  event:
    - push