kind: pipeline
name: "Supabase task CI/CD part"

steps:
- name: "Verify & build"
  image: node:alpine
  environment:
    NEXT_PUBLIC_SUPABASE_URL:
      from_secret: base_url
    NEXT_PUBLIC_SUPABASE_ANON_KEY:
      from_secret: anon_key
  commands:
    - cd supabase_task
    - npm install
    - npm run build
- name: "Build docker image"
    image: plugins/docker
    commands:
      - cd supabase_task
      - docker build . -t supabase-app
      - image_line=$(docker image ls | grep "supabase-app")
      - image_id=$(echo $image | cut -d' ' -f 3)
      - docker tag $image_id maxmoskalenko/supabase_app:${image_id:1:2}
      - docker push maxmoskalenko/supabase_app:${image_id:1:2}

trigger:
  branch:
    - dev
  event:
    - push