kind: pipeline
name: "Supabase task CI/CD part"

steps:
- name: "Verify & build"
  image: node:alpine
  environment:
    NEXT_PUBLIC_SUPABASE_URL:
      from_secret: base_url
    NEXT_PUBLIC_SUPABASE_ANON_KEY:
      from_secret: anon_key
  commands:
    - cd supabase_task
    - npm install
    - npm run build

- name: "Build docker image"
  image: plugins/docker
  environment:
    TOKEN:
      from_secret: docker_token
    NEXT_PUBLIC_SUPABASE_URL:
      from_secret: base_url
    NEXT_PUBLIC_SUPABASE_ANON_KEY:
      from_secret: anon_key
  settings:
    repo: docker.io/maxmoskalenko/supabase_app
    tags: [ "${DRONE_COMMIT_SHA:0:7}","latest" ]
    username:
      from_secret: docker_user
    password:
      from_secret: docker_pass
    build_args_from_env: [ TOKEN NEXT_PUBLIC_SUPABASE_ANON_KEY NEXT_PUBLIC_SUPABASE_URL]
    dockerfile: supabase_task/Dockerfile

trigger:
  branch:
    - dev
  event:
    - push