kind: pipeline
name: "Supabase task CI/CD part"

steps:
- name: "Verify & build"
  image: node:alpine
  commands:
    - cd supabase_task
    - npm install
    - npm run build
    - npm run start
     
trigger:
  branch:
    - dev
  event:
    - push